Update AWSSDK.Core reference to 3.7.0.27 containing SSO changes.
aws/aws-extensions-for-dotnet-cli pull request #173
Opened 2021-05-26 20:16 UTC by ashishdhingra

*Issue #:* #172 

*Description of changes:*
Update AWSSDK.Core reference to 3.7.0.27 containing SSO changes.

___
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-05-26 23:16 UTC, normj requested changes
Please bump up the version of AWSSDK.SecurityToken as well

2021-05-26 23:25 UTC, ashishdhingra commented
> Please bump up the version of AWSSDK.SecurityToken as well

Done.

2021-05-26 23:31 UTC, normj approved these changes

2021-05-28 17:30 UTC, 96malhar approved these changes

2021-06-02 18:16 UTC, merged