bug: Continue gracefully if unable to get Function Url
aws/aws-extensions-for-dotnet-cli pull request #221
Opened 2022-06-02 23:38 UTC by ppittle

*Issue #, if available:*
https://github.com/aws/aws-lambda-dotnet/issues/1188

*Description of changes:*
Continue gracefully if unable to get Function Url when updating a Lambda.  Getting Function Url can occur in regions that do not yet have this functionality or if the current context does not have the appropriate permissions to query function urls.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-06-02 23:44 UTC, ganeshnj requested changes

2022-06-02 23:44 UTC, ganeshnj commented on src/Amazon.Lambda.Tools/Commands/UpdateFunctionConfigCommand.cs
> +            }
Do you know which type of exception is thrown when FunctionURL is not available in the region?

Hiding all the errors will lead to bad experience and non intuitive debugging.

2022-06-02 23:45 UTC, normj approved these changes

2022-06-03 00:29 UTC, normj approved these changes

2022-06-03 02:02 UTC, merged