fix: fixed an issue causing lambda package to hang in CI/CD
aws/aws-extensions-for-dotnet-cli pull request #342
Opened 2024-11-05 20:30 UTC by philasmar

*Description of changes:*
* Switched `UseShellExecute` to `true` from the `dotnet publish` process since that was causing the process to hang in certain situations.
* Switching `UseShellExecute` to `true` required me to update the way we were reading the process output since we are no longer able to redirect stdOut and stdError.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-11-06 17:29 UTC, 96malhar approved these changes

2024-11-07 07:22 UTC, normj requested changes
Copying a side conversation. I think we need to better understand the hanging before making this change. The latest version of this tool is pulled into a lot of CI builds so we need to be really careful. Also I don't like that the new user experience wouldn't show any output till the dotnet command is complete. For a big project that could take awhile for the build to complete and see the output.

2024-11-08 20:22 UTC, philasmar commented
> Copying a side conversation. I think we need to better understand the hanging before making this change. The latest version of this tool is pulled into a lot of CI builds so we need to be really careful. Also I don't like that the new user experience wouldn't show any output till the dotnet command is complete. For a big project that could take awhile for the build to complete and see the output.

I changed the approach to a workaround suggested in https://github.com/dotnet/msbuild/issues/2981.

2024-11-08 21:34 UTC, normj approved these changes

2024-11-08 22:10 UTC, gcbeattyAWS approved these changes

2024-11-08 22:24 UTC, merged

2025-04-09 13:13 UTC, Kuinox commented
I don't know your use case but the danger of this workaround is getting a truncated stdout/stderr.